platform :ios, '12.0'

inhibit_all_warnings!
use_frameworks!

target 'nduri_Example' do
  pod 'nduri', :path => '../'

  target 'nduri_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end
